server:
  port: 9900

spring:
  datasource:
    url: jdbc:mysql://47.113.186.105:3306/rxy_data?serverTimezone=GMT%2B8&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false
    username: bufan
    password: 'V6V4hRa9jfQ-'
    #driver-class-name:  com.mysql.jdbc.Driver
  redis:
    host: 119.3.31.97 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: '6nplgagAtK' # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
logging:
  level:
    root: info
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true


rxy:
  common:
    defaultPicture: http://oss-beta-card.buff-box.com/bufan_user_default.jpg
  wx:
    appId: wx92f63c1b5de7cfc1
    appSecret: 8b8e9a5b43765991a20fbaa02f190307
    wxLoginUrl: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
    wxTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
    wxGetPhoneUrl: https://api.weixin.qq.com/wxa/business/getuserphonenumber?access_token=%s
  oss:
    accessKeyId: LTAI5tS3vsu1N1Hu4M5M39cp
    accessKeySecret: bUiIRgIx2SeloUtFhxhUooce9qw2ib
    endpoint: sts.shanghai.aliyuncs.com
    roleArn: acs:ram::1819172886320555:role/aliyunosstokengeneratorrole
    ossEndpoint: oss-cn-shanghai.aliyuncs.com
    bucketName:  bufan-prod

chatgpt:
  token: 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
  model: text-davinci-003 #可选
  chat-model: gpt-3.5-turbo #可选
  retries: 10 #可选，默认为5
  session-expiration-time: 30 #可选，不填则会话永不过期








